#!/bin/bash
PATH=/sw/bin:/:$PATH
# this is horrific but I can't seem to get it to work another way, any bash experts willing to help
# remove " from filename
var=${1%\"}
var=${var#\"}
sox -t ogg "$var" -t raw -r 44100 -c 2 -w -s - 2>/tmp/oggerr | lame --preset insane -
